### ISSUE TITLE
No file/folder found for package mycrytobot

### ISSUE THREAD

**Issue by TeaCult** [diogomatoschaves/MyCryptoBot#103]
I am on arch 
....
  • Installing rq (1.12.0)
  • Installing seaborn (0.11.2)
  • Installing statsmodels (0.12.2)
  • Installing ta (0.7.0)

Installing the current project: MyCryptoBot (0.1.0)
The current project could not be installed: No file/folder found for package mycryptobot
If you do not want to install the current project use --no-root
gediz@ggArch ~/MyCryptoBot $ ls
dashboard  docker-compose.yml  model           pyproject.toml
data       execution           MODEL_USAGE.md  README.md
database   INSTALLATION.md     poetry.lock     shared
gediz@ggArch ~/MyCryptoBot $ poetry shell
The currently activated Python version 3.11.6 is not supported by the project (>=3.7.1,<3.10).
Trying to find and use a compatible version. 
Using python3 (3.9.18)
Spawning shell within /home/gediz/.cache/pypoetry/virtualenvs/mycryptobot-GfhqIRIN-py3.9
. /home/gediz/.cache/pypoetry/virtualenvs/mycryptobot-GfhqIRIN-py3.9/bin/activate
gediz@ggArch ~/MyCryptoBot $ . /home/gediz/.cache/pypoetry/virtualenvs/mycryptobot-GfhqIRIN-py3.9/bin/activate

**Comment by TeaCult** [comment]
I am also lost in following steps.  The requirements.txt would make it a lot easier. 
Other than that, a vm image qcow2 already adjusted or a docker container already configured press start and run would be fine either. 

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gediz/MyCryptoBot/database/settings.py", line 4, in <module>
    import dj_database_url
ModuleNotFoundError: No module named 'dj_database_url'

**Comment by diogomatoschaves** [comment]
Hi @TeaCult, thanks for your feedback 👌 I've added a `requirements.txt` to the project, as well as pointing to an external package for python version's management. 

As the app is composed of several sub services / apps, there is a docker-compose file that connects all of these, but it still requires some configuration for the local database, if we want to have data persistence. I'll look into a way of minimising the required user configuration.
