### ISSUE TITLE
dashboard not running with docker compose

### ISSUE THREAD

**Issue by Newtoniano** [diogomatoschaves/MyCryptoBot#131]
This is a follow up to #109 , apparently there is still a bug that is preventing the dashboard container from starting successfully. I was able to successfully run it by deleting
```
volumes:
      - ./dashboard:/app
      - /app/node_modules
```
from the dashboard service in the docker-compose file. 

Is there any reason to have these volume bindings or can they be safely removed without losing any functionality or logging capabilities?

Also, is there a reason why there isn't a postgres service in the docker-compose file, and the instructions tell the user to install it in the host system instead? It would make running the bot much easier and very straightforward. I can send a PR for both these things if you want. Let me know your thoughts.

**Comment by diogomatoschaves** [comment]
Hi @Newtoniano, sorry to hear that. It is working for me, so I'm not sure exactly why it is not working. The volumes mapping is there for making it easier to develop the dashboard, as it enables hot-reloading when a dashboard file changes, and so one doesn't have to restart the container for the changes to have effect. 

Are you able to post the error message please?

As for the second part of this issue: I recognise that it is probably indeed a better practice, but other than the advantage of not having to install postgres locally, I dont see any other immediate benefits. The steps described under __database__ on Installation.md will still have to be followed—unless a shell script is added that takes care of that, which could indeed be a good addition. 

Feel free to make that pull request, but please map the volumes as:

```yml
volumes:
      - ./database/data:/var/lib/postgresql/data
```

**Comment by Newtoniano** [comment]
It was happening on my linux machine (which I don't have access to right now so I can't tell you the exact wording),  and the error was something like `unable to read .eslintrc, file doesn't exist or you don't have permission to access this file `, something along these lines. 

Now that I think about it, I believe it's because on that machine I'm running docker commands with `sudo` rather than setting up docker like [this](https://docs.docker.com/engine/install/linux-postinstall/), so I believe there is a conflict there where the root creates the files and then another user is trying to access them later. I tried on my macos machine where I don't have to type `sudo` for docker and it works even with the current docker-compose. So I guess it can stay like this if it's convenient for development, but you might want to mention that you have to do the steps in the link above to run docker as a non-root user if you are encountering errors.

I'll go ahead with the postgres PR instead
