### ISSUE TITLE
Pytest is unable to import some tests

### ISSUE THREAD

**Issue by Newtoniano** [diogomatoschaves/MyCryptoBot#135]
This is an issue I've encountered in vscode, pytest is unable to correctly import 5 tests files and gives errors like these:
```
_pytest.nodes.Collector.CollectError: import file mismatch:
imported module 'test_app' has this __file__ attribute:
  /Volumes/Samsung_T5/Projects/Python/MyCryptoBot/data/tests/service/test_app.py
which is not the same as the test file we want to collect:
  /Volumes/Samsung_T5/Projects/Python/MyCryptoBot/model/tests/service/test_app.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```
This is because these test files have the same name as another test file that's already been imported before, and that creates a conflict.
See [this stackoverflow](https://stackoverflow.com/questions/59444982/import-file-mismatch-errors-occurs-when-running-complete-test-in-pytest-but-pas) for possible solutions.
I'm able to solve the issue by adding a bunch of `__init__.py` files to the affected folders, but it's also possible to change the file names instead. I guess it's easier to go with the init files approach. I can open a PR for this too if you want.

**Comment by diogomatoschaves** [comment]
How are you triggering the tests? I run them separately for each individual module, which speeds up development and also should avoid these conflicts with the same file name. So for example for the data module I would run: 
```shell
python -m pytest data/ --ds=database.settings --cov-report term-missing --cov=./data/service --cov=./data/sources --cov=/.data/tests/ --verbose
```

**Comment by Newtoniano** [comment]
I'm just using the vscode built-in test functionality. It discovers them all and you can run just a subset, for example just the data module. 
<img width="272" alt="image" src="https://github.com/diogomatoschaves/MyCryptoBot/assets/81423796/440e49d7-70eb-4235-ab0c-ce0f8ee473a6">

**Comment by diogomatoschaves** [comment]
Right, I see. I don't see a problem with adding those `__init__` files, so go ahead and submit a PR for that.
