### ISSUE TITLE
Add another strategy

### ISSUE THREAD

**Issue by Juulern** [diogomatoschaves/MyCryptoBot#88]
Hi. I have created a new strategy, but I can't figure out how to add it, and I don't want to mess up anything in the process. The code for the new strategy looks like this:

import pandas as pd
import numpy as np
import talib as ta
from model.strategies._mixin import StrategyMixin
from collections import OrderedDict

class BollingerBandsMACD(StrategyMixin):
    """
    Bollinger Bands with MACD Strategy

    Parameters
    ----------
    bb_length : int
        The length for Bollinger Bands calculation.
    bb_mult : float
        The standard deviation multiplier for Bollinger Bands.
    macd_short : int
        The short period for MACD calculation.
    macd_long : int
        The long period for MACD calculation.
    macd_signal : int
        The signal period for MACD calculation.
    data : pd.DataFrame, optional
        Dataframe of OHLCV data, by default None.
    **kwargs : dict, optional
        Additional keyword arguments to be passed to parent class, by default None.
    """

    def __init__(self, bb_length, bb_mult, macd_short, macd_long, macd_signal, data=None, **kwargs):
        self._bb_length = bb_length
        self._bb_mult = bb_mult
        self._macd_short = macd_short
        self._macd_long = macd_long
        self._macd_signal = macd_signal

        self.params = OrderedDict(bb_length=lambda x: int(x), bb_mult=lambda x: float(x),
                                  macd_short=lambda x: int(x), macd_long=lambda x: int(x),
                                  macd_signal=lambda x: int(x))

        StrategyMixin.__init__(self, data, **kwargs)

    def update_data(self, data):
        data['basis'] = ta.SMA(data['close'], self._bb_length)
        data['dev'] = data['close'].rolling(window=self._bb_length).std()
        data['dev2'] = self._bb_mult * data['dev']
        data['upper2'] = data['basis'] + data['dev2']
        data['lower2'] = data['basis'] - data['dev2']

        macd, signal, _ = ta.MACD(data['close'], self._macd_short, self._macd_long, self._macd_signal)
        data['macd'] = macd
        data['signal'] = signal

        return data

    def _calculate_positions(self, data):
        data['long_condition_bb'] = data['close'].gt(data['upper2']).shift(1)
        data['short_condition_bb'] = data['close'].lt(data['lower2']).shift(1)
        data['long_condition_macd'] = data['macd'].gt(data['signal']).shift(1)
        data['short_condition_macd'] = data['macd'].lt(data['signal']).shift(1)

        data['long_condition'] = data['long_condition_bb'] & data['long_condition_macd']
        data['short_condition'] = data['short_condition_bb'] & data['short_condition_macd']

        data['position'] = 0
        data.loc[data['long_condition'], 'position'] = 1
        data.loc[data['short_condition'], 'position'] = -1

        return data

    def get_signal(self, row=None):
        if row is None:
            return 0

        if row['long_condition']:
            return 1
        elif row['short_condition']:
            return -1
        else:
            return 0
            
Can i use this code, and can you tell me how i can add it?

**Comment by Juulern** [comment]
Have you added any new strategies that are not part of the bot that has been deployed, and have you had success with them? Which of the strategies have the best test results?

**Comment by diogomatoschaves** [comment]
Hi @Juulern, your implementation is almost correct, it's just missing a few things. The correct implementation for the methods `update_data` and `calculate_positions` is as follows (see the comments):
```python
def update_data(self, data):

    data = super().update_data(data) # we must make this call here, so that the returns are calculated.
    
    data['basis'] = ta.SMA(data['close'], self._bb_length)
    data['dev'] = data['close'].rolling(window=self._bb_length).std()
    data['dev2'] = self._bb_mult * data['dev']
    data['upper2'] = data['basis'] + data['dev2']
    data['lower2'] = data['basis'] - data['dev2']
    
    macd, signal, _ = ta.MACD(data['close'], self._macd_short, self._macd_long, self._macd_signal)
    data['macd'] = macd
    data['signal'] = signal
    
    return data
        
def _calculate_positions(self, data):
    data['long_condition_bb'] = data['close'].gt(data['upper2']) # Note that we don't need to shift down here, that is only done when we're calculating the actual return for that timestamp. 
    data['short_condition_bb'] = data['close'].lt(data['lower2'])
    data['long_condition_macd'] = data['macd'].gt(data['signal'])
    data['short_condition_macd'] = data['macd'].lt(data['signal'])
    
    data['long_condition'] = data['long_condition_bb'] & data['long_condition_macd']
    data['short_condition'] = data['short_condition_bb'] & data['short_condition_macd']
    
    data['position'] = 0
    data.loc[data['long_condition'], 'position'] = 1
    data.loc[data['short_condition'], 'position'] = -1
    
    return data
```

The other methods are correct. Also note that you are using a library that is not part of the requirements as default (`talib`), so you need to make sure that you have that installed. You can then save this file on the strategies folder, and make sure that it is imported at the root level of that folder on the file `model/strategies/__init__.py`, so that you can use it just like any other strategy. 

I plan on making the making of new strategies a bit more simplified, so stay tuned for that.

**Comment by diogomatoschaves** [comment]
> Have you added any new strategies that are not part of the bot that has been deployed, and have you had success with them? Which of the strategies have the best test results?

I'm currently more focused on the infrastructure part of this library, but I have personal strategies implemented that are not published on this repository. The goal of this repo is to make it easy for you or anyone to develop your own strategies and deploy them.

**Comment by Juulern** [comment]
So the code should look like this?

import pandas as pd
import numpy as np
import talib as ta
from model.strategies._mixin import StrategyMixin
from collections import OrderedDict

class BollingerBandsMACD(StrategyMixin):
    """
    Bollinger Bands with MACD Strategy

    Parameters
    ----------
    bb_length : int
        The length for Bollinger Bands calculation.
    bb_mult : float
        The standard deviation multiplier for Bollinger Bands.
    macd_short : int
        The short period for MACD calculation.
    macd_long : int
        The long period for MACD calculation.
    macd_signal : int
        The signal period for MACD calculation.
    data : pd.DataFrame, optional
        Dataframe of OHLCV data, by default None.
    **kwargs : dict, optional
        Additional keyword arguments to be passed to parent class, by default None.
    """

    def __init__(self, bb_length, bb_mult, macd_short, macd_long, macd_signal, data=None, **kwargs):
        self._bb_length = bb_length
        self._bb_mult = bb_mult
        self._macd_short = macd_short
        self._macd_long = macd_long
        self._macd_signal = macd_signal

        self.params = OrderedDict(bb_length=lambda x: int(x), bb_mult=lambda x: float(x),
                                  macd_short=lambda x: int(x), macd_long=lambda x: int(x),
                                  macd_signal=lambda x: int(x))

        StrategyMixin.__init__(self, data, **kwargs)

    def update_data(self, data):
        data = super().update_data(data)  # we must make this call here, so that the returns are calculated.

        data['basis'] = ta.SMA(data['close'], self._bb_length)
        data['dev'] = data['close'].rolling(window=self._bb_length).std()
        data['dev2'] = self._bb_mult * data['dev']
        data['upper2'] = data['basis'] + data['dev2']
        data['lower2'] = data['basis'] - data['dev2']

        macd, signal, _ = ta.MACD(data['close'], self._macd_short, self._macd_long, self._macd_signal)
        data['macd'] = macd
        data['signal'] = signal

        return data

    def _calculate_positions(self, data):
        data['long_condition_bb'] = data['close'].gt(data['upper2'])
        data['short_condition_bb'] = data['close'].lt(data['lower2'])
        data['long_condition_macd'] = data['macd'].gt(data['signal'])
        data['short_condition_macd'] = data['macd'].lt(data['signal'])

        data['long_condition'] = data['long_condition_bb'] & data['long_condition_macd']
        data['short_condition'] = data['short_condition_bb'] & data['short_condition_macd']

        data['position'] = 0
        data.loc[data['long_condition'], 'position'] = 1
        data.loc[data['short_condition'], 'position'] = -1

        return data

    def get_signal(self, row=None):
        if row is None:
            return 0

        if row['long_condition']:
            return 1
        elif row['short_condition']:
            return -1
        else:
            return 0

**Comment by Juulern** [comment]
I have installed TA-lib, added the code, and updated "C:\MyCryptoBot\model\strategies_init_.py":

from model.strategies.moving_average import MovingAverage, MovingAverageCrossover, MovingAverageConvergenceDivergence
from model.strategies.mean_reversion import BollingerBands, BollingerBandsMACD
from model.strategies.trend import Momentum

And I have updated "C:\MyCryptoBot\model\strategies\mean_reversion_init_.py":

from .bollinger_bands import BollingerBands
from .bollinger_bands_macd import BollingerBandsMACD

Is there anything else I need to do?

**Comment by Juulern** [comment]
And the code i added here: "C:\MyCryptoBot\model\strategies\mean_reversion\bollinger_bands_macd.py"

**Comment by diogomatoschaves** [comment]
That should be it. You can now experiment with backtesting it (see the examples on how to do it).

The strategy should also now appear on the dropdown list of possible strategies on the frontend app when you create a new trading bot.

**Comment by Juulern** [comment]
But thats the thing. It dosnt apear in the list of strategies when i make a new bot, and i dont understand why?

**Comment by Juulern** [comment]
"C:\MyCryptoBot\model\strategies\mean_reversion\__init__.py":

from model.strategies.mean_reversion import BollingerBands
from model.strategies.mean_reversion import BollingerBandsMACD

"C:\MyCryptoBot\model\strategies\__init__.py":

from model.strategies.moving_average import MovingAverage, MovingAverageCrossover, MovingAverageConvergenceDivergence
from model.strategies.mean_reversion import BollingerBands, BollingerBandsMACD
from model.strategies.trend import Momentum

**Comment by diogomatoschaves** [comment]
You have to update `model/strategies/__init__.py` and `model/strategies/mean_reversion/__init__.py`. The file `mean_reversion_init_.py` and `strategies_init_.py` don't exist.

I tried it myself, and this is the result:

<img width="997" alt="Screenshot 2023-04-30 at 22 37 12" src="https://user-images.githubusercontent.com/11161499/235375272-5e1f4e96-1353-4864-85f8-b6e685d083fa.png">

Also, you have to add the type to the parameters, in order to get the correct input validation on the frontend.

```python
class BollingerBandsMACD(StrategyMixin):
    """
    Bollinger Bands with MACD Strategy

    (...)

    """

    def __init__(self, bb_length: int, bb_mult: int, macd_short: int, macd_long: int, macd_signal: int, data=None, **kwargs):
        self._bb_length = bb_length
        self._bb_mult = bb_mult
        self._macd_short = macd_short
        self._macd_long = macd_long
        self._macd_signal = macd_signal

        self.params = OrderedDict(bb_length=lambda x: int(x), bb_mult=lambda x: float(x),
                                  macd_short=lambda x: int(x), macd_long=lambda x: int(x),
                                  macd_signal=lambda x: int(x))

        StrategyMixin.__init__(self, data, **kwargs)

(...)
```

**Comment by Juulern** [comment]
I started messing around with things too much, and everything ended up crashing. I've spent hours now trying to get everything up and running again. I'm having issues with TA-lib, where versions don't match up with pyproject.toml and poetry.lock. Honestly, I don't understand how to solve this. I'm downloading a fresh version of the bot now and setting it up from scratch.

**Comment by Juulern** [comment]
Now I have downloaded everything again. Since you have already added the strategy, can you share the strategies folder with me so that I don't make any mistakes and also tell me how I can install TA-Lib without breaking everything again? As I mentioned earlier, I am not a coder, so I spend a lot of time troubleshooting. It is incredibly educational, but very frustrating when I cannot get it to work -_-

**Comment by Juulern** [comment]
I think everything should work fine if i just manage to install TA-Lib correctly. I use python Python 3.7.1, anaconda and docker-desktop.

Can you explain what i can do?
