### ISSUE TITLE
Heroku-setup

### ISSUE THREAD

**Issue by Juulern** [diogomatoschaves/MyCryptoBot#89]
I keep getting this error trying to setup:

PS C:\Users\juule> $env:PGUSER = "postgres"
PS C:\Users\juule> $env:PGPASSWORD = **********
PS C:\Users\juule> heroku pg:push mybot DATABASE_URL --app juulern-crypto-bot-data
heroku-cli: Pushing mybot ---> postgresql-curved-58606
pg_dump: last built-in OID is 16383
pg_dump: reading extensions
pg_dump: identifying extension members
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: reading user-defined functions
pg_dump: reading user-defined types
pg_dump: reading procedural languages
pg_dump: reading user-defined aggregate functions
pg_dump: reading user-defined operators
pg_dump: reading user-defined access methods
pg_dump: reading user-defined operator classes
pg_dump: reading user-defined operator families
pg_dump: reading user-defined text search parsers
pg_dump: reading user-defined text search templates
pg_dump: reading user-defined text search dictionaries
pg_dump: reading user-defined text search configurations
pg_dump: reading user-defined foreign-data wrappers
pg_dump: reading user-defined foreign servers
pg_dump: reading default privileges
pg_dump: reading user-defined collations
pg_dump: reading user-defined conversions
pg_dump: reading type casts
pg_dump: reading transforms
pg_dump: reading table inheritance information
pg_dump: reading event triggers
pg_dump: finding extension tables
pg_dump: finding inheritance relationships
pg_dump: reading column info for interesting tables
pg_dump: finding table default expressions
pg_dump: flagging inherited columns in subtables
pg_dump: reading indexes
pg_dump: flagging indexes in partitioned tables
pg_dump: reading extended statistics
pg_dump: reading constraints
pg_dump: reading triggers
pg_dump: reading rewrite rules
pg_dump: reading policies
pg_dump: reading row-level security policies
pg_dump: reading publications
pg_dump: reading publication membership of tables
pg_dump: reading publication membership of schemas
pg_dump: reading subscriptions
pg_dump: reading large objects
pg_dump: reading dependency data
pg_dump: saving encoding = UTF8
pg_dump: saving standard_conforming_strings = on
pg_dump: saving search_path =
pg_dump: saving database definition
pg_dump: dumping contents of table "public.auth_group"
pg_restorepg_dump::  dumping contents of table "public.auth_group_permissions"
connecting to database for restorepg_dump:
 dumping contents of table "public.auth_permission"
pg_dump: dumping contents of table "public.django_content_type"
pg_dump: dumping contents of table "public.django_migrations"
pg_dump: dumping contents of table "public.model_asset"
pg_dump: dumping contents of table "public.model_exchange"
pg_dump: dumping contents of table "public.model_exchangedata"
pg_dump: dumping contents of table "public.model_jobs"
pg_dump: dumping contents of table "public.model_orders"
pg_dump: dumping contents of table "public.model_pipeline"
pg_dump: dumping contents of table "public.model_portfoliotimeseries"
pg_dump: dumping contents of table "public.model_position"
pg_dump: dumping contents of table "public.model_structureddata"
pg_dump: dumping contents of table "public.model_symbol"
pg_dump: dumping contents of table "public.model_trade"
pg_dump: dumping contents of table "public.model_user"
pg_restore: creating TABLE "public.auth_group"
pg_restore: creating SEQUENCE "public.auth_group_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.auth_group_id_seq"
pg_restore: creating TABLE "public.auth_group_permissions"
pg_restore: creating SEQUENCE "public.auth_group_permissions_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.auth_group_permissions_id_seq"
pg_restore: creating TABLE "public.auth_permission"
pg_restore: creating SEQUENCE "public.auth_permission_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.auth_permission_id_seq"
pg_restore: creating TABLE "public.django_content_type"
pg_restore: creating SEQUENCE "public.django_content_type_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.django_content_type_id_seq"
pg_restore: creating TABLE "public.django_migrations"
pg_restore: creating SEQUENCE "public.django_migrations_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.django_migrations_id_seq"
pg_restore: creating TABLE "public.model_asset"
pg_restore: creating TABLE "public.model_exchange"
pg_restore: creating TABLE "public.model_exchangedata"
pg_restore: creating SEQUENCE "public.model_exchangedata_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_exchangedata_id_seq"
pg_restore: creating TABLE "public.model_jobs"
pg_restore: creating SEQUENCE "public.model_jobs_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_jobs_id_seq"
pg_restore: creating TABLE "public.model_orders"
pg_restore: creating TABLE "public.model_pipeline"
pg_restore: creating SEQUENCE "public.model_pipeline_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_pipeline_id_seq"
pg_restore: creating TABLE "public.model_portfoliotimeseries"
pg_restore: creating SEQUENCE "public.model_portfoliotimeseries_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_portfoliotimeseries_id_seq"
pg_restore: creating TABLE "public.model_position"
pg_restore: creating SEQUENCE "public.model_position_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_position_id_seq"
pg_restore: creating TABLE "public.model_structureddata"
pg_restore: creating SEQUENCE "public.model_structureddata_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_structureddata_id_seq"
pg_restore: creating TABLE "public.model_symbol"
pg_restore: creating TABLE "public.model_trade"
pg_restore: creating SEQUENCE "public.model_trade_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_trade_id_seq"
pg_restore: creating TABLE "public.model_user"
pg_restore: creating SEQUENCE "public.model_user_id_seq"
pg_restore: creating SEQUENCE OWNED BY "public.model_user_id_seq"
pg_restore: creating DEFAULT "public.auth_group id"
pg_restore: creating DEFAULT "public.auth_group_permissions id"
pg_restore: creating DEFAULT "public.auth_permission id"
pg_restore: creating DEFAULT "public.django_content_type id"
pg_restore: creating DEFAULT "public.django_migrations id"
pg_restore: creating DEFAULT "public.model_exchangedata id"
pg_restore: creating DEFAULT "public.model_jobs id"
pg_restore: creating DEFAULT "public.model_pipeline id"
pg_restore: creating DEFAULT "public.model_portfoliotimeseries id"
pg_restore: creating DEFAULT "public.model_position id"
pg_restore: creating DEFAULT "public.model_structureddata id"
pg_restore: creating DEFAULT "public.model_trade id"
pg_restore: creating DEFAULT "public.model_user id"
pg_restore: processing data for table "public.auth_group"
pg_restore: error: unrecognized data block type (0) while searching archive
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:905:11)
    at Socket._write (node:net:917:8)
    at doWrite (node:internal/streams/writable:410:12)
    at clearBuffer (node:internal/streams/writable:571:7)
    at onwrite (node:internal/streams/writable:463:7)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:106:10)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (node:internal/streams/readable:773:14)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4047,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by diogomatoschaves** [comment]
What is the command that is making that error?

**Comment by Juulern** [comment]
set PGUSER=postgres&&set PGPASSWORD=<removedpassword, but my db-password>&&heroku pg:push mybot DATABASE_URL --app juulern-crypto-bot-data

**Comment by Juulern** [comment]
Ill pay you 50$ to install everything for me with teamviewer.

**Comment by diogomatoschaves** [comment]
> set PGUSER=postgres&&set PGPASSWORD=<removedpassword, but my db-password>&&heroku pg:push mybot DATABASE_URL --app juulern-crypto-bot-data

You mean this command?

```

heroku pg:reset --app <YOUR_UNIQUE_DATA_APP_NAME>
PGUSER=<pg_username> PGPASSWORD=<pg_password> heroku pg:push mycryptobot DATABASE_URL --app <YOUR_UNIQUE_DATA_APP_NAME>
```

**Comment by diogomatoschaves** [comment]
You are talking about the Heroku setup, but that command is for the local installation.

**Comment by Juulern** [comment]
Ive tried so many things man. Would you do the Heroku-setup for me on teamviewer for 50$.

**Comment by Juulern** [comment]
Uploading the database
In order to upload the data we have locally into the remote database, run the following commands:

heroku pg:reset --app <YOUR_UNIQUE_DATA_APP_NAME>
PGUSER=<pg_username> PGPASSWORD=<pg_password> heroku pg:push mycryptobot DATABASE_URL --app <YOUR_UNIQUE_DATA_APP_NAME>
Finally, running the following command will activate the worker dyno on the model app:

heroku ps:scale worker=1 --app <YOUR_UNIQUE_MODEL_APP_NAME>

**Comment by Juulern** [comment]
Is that a no for doing it for me? ^^

**Comment by diogomatoschaves** [comment]
I'll send you a text tomorrow when I'm available

**Comment by Juulern** [comment]
Nice thanks!

**Comment by Juulern** [comment]
You know about when you have time today? So i dont be out when you Are avaiable.

**Comment by diogomatoschaves** [comment]
Hey, wanna do it in half an hour? send me your email

**Comment by Juulern** [comment]
Juulern2011@gmail.com

**Comment by Juulern** [comment]
In half hour is ok for me 👍

**Comment by Juulern** [comment]
Teamviewer id 1765119614
Pass 8fe82yng

I pay on paypal?

**Comment by diogomatoschaves** [comment]
You don't have to pay anything, I'll see if I can help you

**Comment by diogomatoschaves** [comment]
@Juulern have a look at this answer, and see if it works for you

https://stackoverflow.com/a/23723824

**Comment by Juulern** [comment]
So i manage to push database. I ran into a new error:

I tried a lot of different things here also, but i cannot figure out what
im doing wrong.

ons. 3. mai 2023 kl. 22:26 skrev Diogo Matos Chaves <
***@***.***>:

**Comment by Juulern** [comment]
Now it looks like everything is building correct, but i still get a few errors. You have time for a small session later today, just to make the last needed changes?

**Comment by diogomatoschaves** [comment]
I have a bit of time now

**Comment by Juulern** [comment]
Im still in work. So im not near computer. You have time later?

**Comment by diogomatoschaves** [comment]
unfortunately no :(

**Comment by Juulern** [comment]
Im on computer, but not the same one. Is it possible to do this remotly on this computer, since everything is now uploaded to cloud?

**Comment by diogomatoschaves** [comment]
depends on the type of errors 🤷‍♂️ Maybe it's better to wait for a suitable time

**Comment by Juulern** [comment]
Just check quick?

**Comment by Juulern** [comment]
Here are my TeamViewer ID number and connection password.
Please use them to start a remote support session with me.

TeamViewer ID: 553 046 257
Your Password: k8qav2kh

**Comment by Juulern** [comment]
Hello. I have set up the bot locally again and it is running as it should. Do you have time to show me live how to add new strategies? I'm afraid of making mistakes because it takes so much time to clean up. I never managed to run it on Heroku.
